# Generated by Django 4.2.27 on 2026-01-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('ration_card', 'نظام البطاقة التموينية'), ('commercial_flour', 'نظام الطحين الصفر التجاري')], max_length=20, verbose_name='نوع النظام')),
                ('quota_number', models.PositiveIntegerField(help_text='من 1 إلى 12', verbose_name='رقم الحصة/الدفعة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('quota_number__gte', 1), ('quota_number__lte', 12)), name='valid_quota_number'),
        ),
    ]
