# Generated by Django 4.2.27 on 2026-01-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم/البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sessions_manager.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-created_at'],
            },
        ),
    ]
