# Generated by Django 4.2.27 on 2026-01-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='اسم المشتري')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('quantity_kilos', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الكمية (كيلو)')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='رقم القائمة/الفاتورة')),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الطن (1000 كيلو)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الكلي')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('debt', 'دين'), ('partial', 'جزئي')], default='cash', max_length=20, verbose_name='نوع الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sessions_manager.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'مبيعة',
                'verbose_name_plural': 'المبيعات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
