# Generated by Django 4.2.27 on 2026-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0003_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'بيع', 'verbose_name_plural': 'المبيعات'},
        ),
        migrations.AddField(
            model_name='sale',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع المادة'),
        ),
    ]
