# Generated by Django 4.2.27 on 2026-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0004_alter_sale_options_sale_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='item_type',
            field=models.CharField(choices=[('flour', 'طحين'), ('bran', 'نخالة'), ('impurities', 'شوائب'), ('wheat', 'حنطة'), ('broken_wheat', 'كسر حنطة')], default='flour', max_length=50, verbose_name='نوع المادة'),
        ),
    ]
