# Generated by Django 4.2.27 on 2026-01-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0005_alter_sale_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات / لشنو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_entries', to='sessions_manager.sale', verbose_name='البيع المرتبط')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='sessions_manager.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'دين',
                'verbose_name_plural': 'الديون',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
