# Generated by Django 4.2.27 on 2026-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0006_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='entry_type',
            field=models.CharField(choices=[('debt', 'دين (عليه)'), ('payment', 'تسديد (له/منه)')], default='debt', max_length=10, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
