# Generated by Django 4.2.27 on 2026-01-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الكمية')),
                ('silo_name', models.CharField(max_length=255, verbose_name='اسم السايلو')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='رقم القائمة')),
                ('transport_price_per_ton', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر نقل الطن')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الكلي')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='السلف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_jobs', to='sessions_manager.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'نقلية سائق',
                'verbose_name_plural': 'نقليات السواقين',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
