# Generated by Django 4.2.27 on 2026-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0009_driverjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='entry_type',
            field=models.CharField(choices=[('debt', 'دين للبيت (عليه)'), ('payment', 'تسديد للبيت (منه)'), ('liability', 'دين للمطحنة (دائن)'), ('our_payment', 'تسديد من المطحنة (مدين)')], default='debt', max_length=20, verbose_name='نوع العملية'),
        ),
    ]
