# Generated by Django 4.2.27 on 2026-01-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0010_alter_debt_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='entry_type',
            field=models.CharField(choices=[('debt', 'دين (عليه)'), ('payment', 'تسديد (منه)'), ('liability', 'دين (دائن)'), ('our_payment', 'تسديد (مدين)')], default='debt', max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(choices=[('mohammad_jamil', 'محمد جميل (50%)'), ('abdullah_khalid', 'عبدالله خالد (40%)'), ('bashir_sabhan', 'بشير سبهان (10%)')], max_length=50, verbose_name='اسم الشريك')),
                ('type', models.CharField(choices=[('deposit', 'إيداع (منه)'), ('withdrawal', 'سحب (له)')], max_length=20, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_transactions', to='sessions_manager.session', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'عملية شريك',
                'verbose_name_plural': 'عمليات الشركاء',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
