# Generated by Django 4.2.27 on 2026-01-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0011_alter_debt_entry_type_partnertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverjob',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القائمة'),
        ),
        migrations.AlterField(
            model_name='driverjob',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='driverjob',
            name='silo_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السايلو'),
        ),
        migrations.AlterField(
            model_name='driverjob',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='المبلغ الكلي'),
        ),
        migrations.AlterField(
            model_name='driverjob',
            name='transport_price_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='سعر نقل الطن'),
        ),
    ]
