# Generated by Django 4.2.27 on 2026-01-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0012_alter_driverjob_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'إيداع (منه)'), ('withdrawal', 'سحب (له)'), ('profit', 'أرباح (حصة)')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
