# Generated by Django 4.2.27 on 2026-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0013_alter_partnertransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم السائق')),
                ('is_sales_driver', models.BooleanField(default=False, verbose_name='سائق مبيعات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السواق',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'يطلبنا'), ('withdrawal', 'نطلبه'), ('profit', 'أرباح (حصة)')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
