# Generated by Django 4.2.27 on 2026-01-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0014_driver_alter_partnertransaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_sales_driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='category',
            field=models.CharField(choices=[('mill', 'سائق مطحنة (يظهر في السواق)'), ('sales', 'سائق مبيعات (يظهر في المبيعات)'), ('both', 'الاثنين معاً')], default='both', max_length=20, verbose_name='التصنيف'),
        ),
    ]
