# Generated by Django 4.2.27 on 2026-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0015_remove_driver_is_sales_driver_driver_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='default_silo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='السايلو الافتراضي'),
        ),
    ]
